# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 16:36
from __future__ import unicode_literals
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=timezone.now, upload_to='/blog/thumb'),
        ),
    ]
