# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_w600_h400',
        ),
    ]
