# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180913_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_w600_h400',
            new_name='imagew600h400',
        ),
    ]
